name       : vala-panel-appmenu
version    : 0.5.6
release    : 4
source     :
    - https://github.com/rilian-la-te/vala-panel-appmenu/releases/download/0.5.6/vala-panel-appmenu-0.5.6.tar.gz : a8497076f34825e0db364ed142f05719d0c8f5f939a7796fe92bca84bbef1b49
license    : GPL-3.0
component  :
    - desktop.utils
    - mate-desktop : desktop.mate
    - budgie-desktop : desktop.budgie
summary    : Global menu for Vala Panel (and others)
libsplit   : no
description: |
    A GTK3 global menu implementation for Vala, Budgie, MATE, and XFCE panels
patterns   :
    - mate-desktop :
        - /usr/lib64/mate-panel/appmenu-mate
        - /usr/share/dbus-1/services/org.mate.panel.applet.AppmenuAppletFactory.service
        - /usr/share/mate-panel/applets/org.vala-panel.appmenu.mate-panel-applet
    - budgie-desktop :
        - /usr/lib64/budgie-desktop/plugins
rundeps    :
    - mate-desktop : vala-panel-appmenu
    - budgie-desktop : vala-panel-appmenu
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libmatepanelapplet-4.0)
    - vala
setup      : |
    %cmake -DENABLE_UNITY_GTK_MODULE=ON .
build      : |
    %make
install    : |
    %make_install
