name       : vala-panel-appmenu
version    : 0.4.4
release    : 3
source     :
    - https://github.com/rilian-la-te/vala-panel-appmenu/releases/download/0.4.4/vala-panel-appmenu-0.4.4.tar.gz : 138913c256f3aa069e08ebd07d1ada3dc8cb60d9ac5ad941fd11f6dc5f5eae4b
license    : GPL-3.0
component  :
    - desktop.utils
    - mate-desktop: desktop.mate
    - budgie-desktop: desktop.budgie
summary    : Global menu for Vala Panel (and others)
libsplit   : no
description: |
    A GTK3 global menu implementation for Vala, Budgie, MATE, and XFCE panels
patterns   :
    - mate-desktop:
        - /usr/lib64/mate-panel/appmenu-mate
        - /usr/share/dbus-1/services/org.mate.panel.applet.AppmenuAppletFactory.service
        - /usr/share/mate-panel/applets/org.vala-panel.appmenu.mate-panel-applet
    - budgie-desktop:
        - /usr/lib64/budgie-desktop/plugins
rundeps    :
    - mate-desktop: vala-panel-appmenu
    - budgie-desktop: vala-panel-appmenu
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libmatepanelapplet-4.0)
    - vala
setup      : |
    %cmake -DENABLE_UNITY_GTK_MODULE=ON .
build      : |
    %make
install    : |
    %make_install
