name       : vala-panel-appmenu
version    : 0.7.1
release    : 9
source     :
    - git|https://gitlab.com/vala-panel-project/vala-panel-appmenu.git : 698a2df47af8d8b19ebd4ef604b0118c1715a407
license    : GPL-3.0-or-later
component  :
    - desktop.utils
    - mate-desktop : desktop.mate
    - budgie-desktop : desktop.budgie
libsplit   : no
summary    : Global menu for Vala Panel (and others)
description: |
    A GTK3 global menu implementation for Vala, Budgie, MATE, and XFCE panels
patterns   :
    - mate-desktop :
        - /usr/lib64/mate-panel
        - /usr/libexec/mate-panel
        - /usr/share/dbus-1/services/org.mate.panel.applet.AppmenuAppletFactory.service
        - /usr/share/mate-panel/applets/org.vala-panel.appmenu.mate-panel-applet
    - budgie-desktop :
        - /usr/lib64/budgie-desktop/plugins
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libbamf3)
    - pkgconfig(libmatepanelapplet-4.0)
    - vala
rundeps    :
    - mate-desktop : vala-panel-appmenu
    - budgie-desktop : vala-panel-appmenu
setup      : |
    %patch -p1 < $pkgfiles/0001-Tweak-CMake-for-bamf-check.patch
    %cmake -DENABLE_UNITY_GTK_MODULE=ON .
build      : |
    %make
install    : |
    %make_install
